version: 2
updates:
- package-ecosystem: docker
  directories:
  - "/base/**"
  schedule:
    interval: weekly
  open-pull-requests-limit: 3
  groups:
    images-minor-and-patch:
      update-types:
      - minor
      - patch
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 3
  groups:
    actions-minor-and-patch:
      update-types:
      - minor
      - patch
