apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - loki/configmap.yaml
  - loki/pvc.yaml
  - loki/deployment.yaml
  - loki/service.yaml
  - alloy/rbac.yaml
  - alloy/configmap.yaml
  - alloy/daemonset.yaml
  - alloy/service.yaml
