apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tempo-storage
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  # storageClassName: standard  # uncomment and set for your cluster
